{
    'name': "Car Order",
    'summary': """
        Car OrderModule...
    """,
    'description': """""",
    'author': "Around Enterprise Consulting Co., Ltd.",
    'website': "https://www.around.co.th",
    "version": "15.0.0.8.0",
    "depends": [
        'base',
        'product',
        'account',
        'sale',
        'crm',
        'sales_team',
        'hr',
        'fleet_product_link',
        'stock',
        'report_vehicle_pipeline',
        'purchase',
        'purchase_requisition',
        'account_batch_payment',
        'custom_partner',
    ],
    "data": [
        "data/ir_sequence_data.xml",
        "data/paper_format.xml",
        "security/security.xml",
        "report/car_order_report.xml",
        "report/car_order_template.xml",
        "report/quotation_template.xml",
        "security/ir.model.access.csv",
        "views/res_config_settings_view.xml",
        "views/actions.xml",
        "views/product_template.xml",
        "views/car_order.xml",
        'views/account_stock_card_view.xml',
        'views/purchase_requisition.xml',
        'views/purchase_order.xml',
        "views/res_users.xml",
        "views/sale_order.xml",
        "views/crm_lead.xml",
        "views/account_move.xml",
        "views/account_batch_payment.xml",
    ]
}
